- [ ] Multi-threaded invoicing engine
- [ ] State-machine based
- [ ] Guard scriptable
- [ ] Reporting
- [ ] PDF, Doc generation
- [ ] Remittance, Disputes, Credits, Memos
- [ ] Tax Tables(?)
- [ ] Client Contacts
- [ ] Products

- [x] MySQL
- [ ] MongoDB
- [x] PostgreSQL
- [x] CouchDB
- [ ] Oracle/MSSQL 
